// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cl.proyectoads;

import cl.proyectoads.Clase;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Clase_Roo_Configurable {
    
    declare @type: Clase: @Configurable;
    
}
