// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cl.arquitectura.proyectoads.domain;

import cl.arquitectura.proyectoads.domain.TipoPersona;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoPersona_Roo_Configurable {
    
    declare @type: TipoPersona: @Configurable;
    
}
